# Generated by Django 4.0.3 on 2022-03-19 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_admin_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token_admin',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
