# Generated by Django 3.2.6 on 2022-03-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls_create',
            options={'ordering': ['-poll_name']},
        ),
    ]
