# Generated by Django 4.0.3 on 2022-03-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_polls_create_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls_create',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
