# Generated by Django 4.0.3 on 2022-03-21 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_polls_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls_create',
            name='voted_list',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
