# Generated by Django 4.0.3 on 2022-03-21 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_polls_create_voted_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls_create',
            name='voted_list',
        ),
        migrations.AddField(
            model_name='polls_create',
            name='voted_list2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
