# Generated by Django 4.0.3 on 2022-03-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_remove_polls_create_voted_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls_create',
            name='voted_list2',
        ),
        migrations.AddField(
            model_name='polls_create',
            name='voted_list3',
            field=models.IntegerField(default=0),
        ),
    ]
