# Generated by Django 4.0.3 on 2022-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_remove_polls_create_voted_list3'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls_create',
            name='voted_info',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
