# Generated by Django 4.0.3 on 2022-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_remove_polls_create_voted_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls_create',
            name='is_current_user_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polls_create',
            name='is_poll_created_user_voted',
            field=models.BooleanField(default=False),
        ),
    ]
